### PR TITLE
fix: add unique constraint to username and email

### PR DESCRIPTION
**Pull request by emmanuel-carreira**
Add unique constraint to username and email columns in user table

### CODE REVIEW

**Comment by emmanuel-carreira** [comment]
[Add unique constraint to username and email](https://trello.com/c/L1LMPDR6/12-add-unique-constraint-to-username-and-email)

**Review by viiniciuspaes — COMMENTED** [review]
Does both those fields need to be unique ? usually only one unique field is need to user/table validation. In this regard to avoid multiple users with the same email there must be a handler for the front end calls so things like this can have proper validation.

**Comment by emmanuel-carreira** [comment]
I tuned both username and e-mail in unique fields so we don't rely too much on front-end and/or handler validation since we can assure this uniqueness on database level.

And if them both need to be unique, well, that depends on how we'll let the user log in. If we let the user choose which field he/she wants to use to authenticate, them i think both of them need to be unique. What do you think?

**Comment by viiniciuspaes** [comment]
I think we can validate this on the controller so we can avoid security problems and DB problems and there is no warm in have both fields unique as you said.

**Review by FernandoCCNeto — APPROVED** [review]

**Pull request merged**
